[settings]
paranoid = false
always_keep_download = false
always_keep_install = true
auto_install = true
exec_auto_install = true
experimental = true
lockfile = true
log_level = "error"
disable_backends = ["asdf"]

[settings.status]
show_env = true
show_tools = true
missing_tools = "always"

[env]
# for gcloud
MISE_FETCH_REMOTE_VERSIONS_TIMEOUT = "25s"

### ALIASES #################################################################
[tool_alias]
docker-compose = "aqua:docker/compose"
flux-operator  = "github:controlplaneio-fluxcd/flux-operator"
flux9s         = "github:dgunzy/flux9s"
forward-email  = "github:ginsys/forward-email"
garage-webui   = "github:khairul169/garage-webui"
goit-who       = "github:sinclairtarget/git-who"
gitlab-cli     = "gitlab:gitlab-org/cli"
hubble         = "github:cilium/hubble"
hurlfmt        = "github:Orange-OpenSource/hurl"
korb           = "github:BeryJu/korb"
kubewall       = "github:kubewall/kubewall"
nats-cli       = "github:nats-io/natscli"
nats-server    = "github:nats-io/nats-server"
nats-top       = "github:nats-io/nats-top"
nsc            = "github:nats-io/nsc"
satty          = "github:gabm/Satty"
snitch         = "github:karol-broda/snitch"
### ALIASES #################################################################


### TOOLS ###################################################################
[tools]
age                                             = { version = "latest" }
argocd                                          = { version = "latest" }
awscli                                          = { version = "latest" }
azure-cli                                       = { version = "latest" }
bat                                             = { version = "latest" }
bitwarden                                       = { version = "latest" }
btop                                            = { version = "latest" }
bun                                             = { version = "latest" }
cilium-cli                                      = { version = "latest", exe = "cilium" }
cilium-hubble                                   = { version = "latest" }
civo                                            = { version = "latest", exe = "civo" }
clusterctl                                      = { version = "latest" }
cmctl                                           = { version = "latest" }
cosign                                          = { version = "latest" }
difftastic                                      = { version = "latest", exe = "difft" }
direnv                                          = { version = "latest", exe = "direnv" }
docker-compose                                  = { version = "2.30.3", rename_exe = "docker-compose" }
doctl                                           = { version = "latest" }
dyff                                            = { version = "latest", exe = "dyff" }
eksctl                                          = { version = "latest" }
fd                                              = { version = "latest" }
flux-operator                                   = { version = "latest", exe = "flux-operator" }
flux2                                           = { version = "latest" }
flux9s                                          = { version = "latest" }
forward-email                                   = { version = "v0.2.0-alpha.2" }
fx                                              = { version = "latest", exe = "fx" }
garage-webui                                    = { version = "latest" }
gcloud                                          = { version = "latest" }
git-who                                         = { version = "latest" }
github-cli                                      = { version = "latest" }
gitlab-cli                                      = { version = "latest" }
go                                              = { version = "latest" }
go-containerregistry                            = { version = "latest", exe = "crane" }
grpcurl                                         = { version = "latest", exe = "grpcurl" }
hcloud                                          = { version = "latest" }
helm                                            = { version = "latest" }
hubble                                          = { version = "latest", exe = "hubble" }
hugo                                            = { version = "latest" }
hurl                                            = { version = "latest", exe = "hurl" }
hurlfmt                                         = { version = "latest", exe = "hurlfmt" }
jb                                              = { version = "latest" }
jd                                              = { version = "latest", exe = "jd" }
jless                                           = { version = "latest" }
jnv                                             = { version = "latest", exe = "jnv" }
jqp                                             = { version = "latest", exe = "jqp" }
k9s                                             = { version = "latest" }
kind                                            = { version = "latest" }
kompose                                         = { version = "latest" }
korb                                            = { version = "latest", exe = "korb" }
krew                                            = { version = "latest" }
kube-capacity                                   = { version = "latest" }
kube-score                                      = { version = "latest" }
kubebuilder                                     = { version = "latest" }
kubecolor                                       = { version = "latest" }
kubeconform                                     = { version = "latest" }
kubectl                                         = { version = "latest" }
kubent                                          = { version = "latest" }
kubeseal                                        = { version = "latest" }
kubesec                                         = { version = "latest" }
kubeshark                                       = { version = "latest", exe = "kubeshark" }
kubespy                                         = { version = "latest" }
kubewall                                        = { version = "latest" }
kubie                                           = { version = "latest" }
kustomize                                       = { version = "latest" }
nats-server                                     = { version = "latest", exe = "nats-server" }
nats-cli                                        = { version = "latest", exe = "nats" }
nats-top                                        = { version = "latest" }
"vfox:mise-plugins/vfox-neovim"                 = { version = "latest" }
node                                            = { version = "latest" }
nova                                            = { version = "latest" }
npm                                             = { version = "latest" }
nsc                                             = { version = "latest" }
"go:github.com/nats-io/nkeys/nk"                = { version = "latest" }
oras                                            = { version = "latest", exe = "oras" }
osv-scanner                                     = { version = "latest" }
pkl                                             = { version = "latest", exe = "pkl" }
pluto                                           = { version = "latest" }
pnpm                                            = { version = "latest" }
popeye                                          = { version = "latest" }
rbac-lookup                                     = { version = "latest" }
regsync                                         = { version = "latest" }
regbot                                          = { version = "latest" }
regctl                                          = { version = "latest" }
ripgrep                                         = { version = "latest", exe = "rg" }
rust                                            = { version = "latest" }
satty                                           = { version = "latest", exe = "satty" }
scaleway-cli                                    = { version = "latest" }
slsa-verifier                                   = { version = "latest" }
snitch                                          = { version = "latest" }
sops                                            = { version = "latest" }
starship                                        = { version = "latest" }
stern                                           = { version = "latest" }
superfile                                       = { version = "latest", exe = "spf" }
talhelper                                       = { version = "latest" }
talosctl                                        = { version = "latest", exe = "talosctl" }
updatecli                                       = { version = "latest", exe = "updatecli" }
usage                                           = { version = "latest" }
uv                                              = { version = "latest" }
vcluster                                        = { version = "latest" }
velero                                          = { version = "latest" }
yamlfmt                                         = { version = "latest" }
yazi                                            = { version = "latest", exe = "yazi" }
yq                                              = { version = "latest" }
"github:vicanso/zedis"                          = "latest"
"github:zitadel/zitadel"                        = "latest"
"github:jedi4ever/addt" = "latest"
"github:gruntwork-io/git-xargs" = "latest"
